xcovs = {[-1 10 1], [-2 20 2], [-3 30 3];
         [],        [-4 40 4], [-5 50 5];
         [],        [],        [-6 60 6]};

C = mysort.noise.xcov2timeC(xcovs);
disp(C)

% it is correct that the -1 is in the top right of the first subblock!
% suppose: 
%         a1 a2 a3 a4 a5 a6 ...
% X =     b1 b2 b3 b4 b5 b6 ...
%         c1 c2 c3 c4 c5 c6 ...
% 
%   then the channel embedding with maxlag = 2 of X is
%   
%         a1 a2 a3 a4 a5 a6 ...
%         a2 a3 a4 a5 a6 ...            
%         a3 a4 a5 a6 ...                    
%         b1 b2 b3 b4 b5 b6 ...
% X_ =    b2 b3 b4 b5 b6 ...
%         b3 b4 b5 b6 ...
%         c1 c2 c3 c4 c5 c6 ...
%         c2 c3 c4 c5 c6 ...
%         c3 c4 c5 c6 ...
% 
% and thus X_ * X_' is
% 
%         var(a,a, 0) var(a,a,-1) var(a,a,-2)   var(a,b, 0) var(a,b,-1) var(a,b,-2) ...
%                     var(a,a, 0) var(a,a,-1)               var(a,b, 0) var(a,b,-1) ...
%                                 var(a,a, 0)                           var(a,b, 0) ...
%         var(b,a, 0) var(b,a,-1) var(b,a,-2)   var(b,b, 0) var(b,b,-1) var(b,b,-2) ...
%                     var(b,a, 0) var(b,a,-1)               var(b,b, 0) var(b,b,-1) ...
%                                 var(b,a, 0)                           var(b,b, 0) ...
% CC2 =  ...
% 
% 
% 
% since var(b,a,-1) == var(a,b,1):
% 
%         var(a,a, 0) var(a,a,-1) var(a,a,-2)   var(a,b, 0) var(a,b,-1) var(a,b,-2) ...
%                     var(a,a, 0) var(a,a,-1)               var(a,b, 0) var(a,b,-1) ...
%                                 var(a,a, 0)                           var(a,b, 0) ...
%         var(a,b, 0) var(a,b, 1) var(a,b, 2)   var(b,b, 0) var(b,b,-1) var(b,b,-2) ...
%                     var(a,b, 0) var(a,b, 1)               var(b,b, 0) var(b,b,-1) ...
%                                 var(a,b, 0)                           var(b,b, 0) ...
% CC2 =  ...
% 
% 
% and thus the block(2,1) is equal to the block(1,2)':
% 
%        CC2aa  CC2ab  CC2ac
% CC2 =  CC2ab' CC2bb  CC2bc
%        CC2ac' CC2ab' CC2cc
% 
% 
% for the time embedding we have
%    
%     
%     
%         a1 a2 a3 a4 a5 a6 ...
%         b1 b2 b3 b4 b5 b6 ...
%         c1 c2 c3 c4 c5 c6 ...
%         a2 a3 a4 a5 a6 ...            
% X__ =   b2 b3 b4 b5 b6 ...        
%         c2 c3 c4 c5 c6 ...        
%         a3 a4 a5 a6 ...                    
%         b3 b4 b5 b6 ...
%         c3 c4 c5 c6 ...
% 
% and thus for CT2 = X__ * X__'
% 
% 
%         var(a,a, 0) var(a,b, 0) var(a,c, 0)    var(a,a,-1) var(a,b,-1) var(a,c,-1) ...
%         var(b,a, 0) var(b,b, 0) var(b,c, 0)    var(b,a,-1) var(b,b,-1) var(b,c,-1) ...
%         var(c,a, 0) var(c,b, 0) var(c,c, 0)    var(c,a,-1) var(c,b,-1) var(c,c,-1) ...
%         
%         var(a,a, 1) var(a,b, 1) var(a,c, 1)    var(a,a, 0) var(a,b, 0) var(a,c, 0) ...
% CT2 =   var(b,a, 1) var(b,b, 1) var(b,c, 1)    var(b,a, 0) var(b,b, 0) var(b,c, 0) ...
%         var(c,a, 1) var(c,b, 1) var(c,c, 1)    var(c,a, 0) var(c,b, 0) var(c,c, 0) ...
%         
%         ...
%         ...
%         ...
% 
%                                 
% again, since var(a,b,-1) == var(b,a, 1):
% 
%         var(a,a, 0) var(a,b, 0) var(a,c, 0)    var(a,a,-1) var(a,b,-1) var(a,c,-1) ...
%         var(b,a, 0) var(b,b, 0) var(b,c, 0)    var(b,a,-1) var(b,b,-1) var(b,c,-1) ...
%         var(c,a, 0) var(c,b, 0) var(c,c, 0)    var(c,a,-1) var(c,b,-1) var(c,c,-1) ...
%         
%         var(a,a,-1) var(b,a,-1) var(c,a,-1)    var(a,a, 0) var(a,b, 0) var(a,c, 0) ...
% CT2 =   var(a,b,-1) var(b,b,-1) var(c,b,-1)    var(b,a, 0) var(b,b, 0) var(b,c, 0) ...
%         var(a,c,-1) var(b,c,-1) var(c,c,-1)    var(c,a, 0) var(c,b, 0) var(c,c, 0) ...
%         
%         ...
%         ...
%         ...
%         
% this means the block(2,1) is equal to block(1,2)':
% 
%  
%        CT0   CT11  CT22 
% CT2 =  CT11' CT0   CT11
%        CT22' CT11' CT0
%        
% 
% and this makes it clear that this representation is easier to handle since
% we only have to store one block-row or block-column of CT2 but we will have 
% to store the whole CC2 matrix.

