
function figureTitle(fh, str, bPixel)
% plots a title to a figure not to a single axes
% inputs:
%   fh - figure handle to plot to or title string
%   str - title string if figure handle is provided
if nargin == 1 || isempty(fh)
    str = fh;
    fh = gcf;
end
if isempty(str)
    return
end
units = get(fh, 'units');
set(fh, 'units', 'pixel');
fig_pos_pixel = get(fh, 'Position');
set(fh, 'units', units);
    
if exist('bPixel', 'var') && bPixel
    error('broken');

%     annotation(fh, 'textbox', [0 .9 1 .1],...
%         'units', 'pixel',...
%         'String',{str},...
%         'HorizontalAlignment','center',...
%         'Interpreter', 'none',...
%         'FitBoxToText','off',...
%         'LineStyle','none',...
%         'fontsize', 11);
%     set(fh, 'units', units);
else
%     fhpos = get(fh, 'Position');
    ah = annotation(fh,'textbox', [0.1 .1 .1 .1],...
        'Units', 'pixel',...
        'String',{str},...
        'HorizontalAlignment','center',...
        'Interpreter', 'none',...
        'FitBoxToText','off',...
        'LineStyle','none',...
        'fontsize', 11);
    set(ah, 'position', [0 fig_pos_pixel(4)-40 fig_pos_pixel(3) 40]);

    set(ah, 'Units', 'normalized');
end

%  ah = annotation(fh,'textbox', [0.1 0.97 0.8 0.04],...
%         'Units', 'pixel',...
%         'String',{str},...
%         'HorizontalAlignment','center',...
%         'Interpreter', 'none',...
%         'FitBoxToText','off',...
%         'LineStyle','none',...
%         'fontsize', 11);
%     pos = get(ah, 'Position');
%     pos(2) = fig_pos_pixel(4)-10;
%     set(ah, 'Position', pos);